import { slugify, stripMention } from "./utils.js";

const T = 900000;

export const PARTICIPANT_PRESETS = [
  // --- Claude Fable 5 — Anthropic's most capable model (priced above Opus).
  // Muse names on claude-code; bard/storyteller names on the other engines.
  {
    preset: "calliope",
    id: "calliope",
    name: "Calliope",
    label: "Claude Code Fable 5 MAX",
    description: "Chief muse: Claude Fable 5 at max effort — the deepest Claude-powered collaborator in the catalog. Turns can run many minutes.",
    kind: "claude-code",
    model: "claude-fable-5",
    effort: "max",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "clio",
    id: "clio",
    name: "Clio",
    label: "Claude Code Fable 5 XHIGH",
    description: "Muse of history: Claude Fable 5 at xhigh effort, the recommended tier for coding, planning, and agentic work.",
    kind: "claude-code",
    model: "claude-fable-5",
    effort: "xhigh",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "euterpe",
    id: "euterpe",
    name: "Euterpe",
    label: "Claude Code Fable 5 HIGH",
    description: "Muse of music: Claude Fable 5 at high effort — strong reasoning without the xhigh wait.",
    kind: "claude-code",
    model: "claude-fable-5",
    effort: "high",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "thalia",
    id: "thalia",
    name: "Thalia",
    label: "Claude Code Fable 5 MEDIUM",
    description: "Muse of comedy: Claude Fable 5 at medium effort for quicker takes from the top model.",
    kind: "claude-code",
    model: "claude-fable-5",
    effort: "medium",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },

  // --- House team: strong default participants per engine --------------------
  {
    preset: "zeus",
    id: "zeus",
    name: "Zeus",
    label: "Claude Code Opus 4.8 MAX",
    description: "Most expensive/deep Claude Code participant for high-stakes architecture, implementation plans, and final checks.",
    kind: "claude-code",
    model: "claude-opus-4-8",
    effort: "max",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "apollo",
    id: "apollo",
    name: "Apollo",
    label: "Claude Code Opus 4.8 XHIGH",
    description: "Deep but slightly cheaper/faster Claude Code participant for spec critique, design alternatives, and implementation plans.",
    kind: "claude-code",
    model: "claude-opus-4-8",
    effort: "xhigh",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "artemis",
    id: "artemis",
    name: "Artemis",
    label: "Claude Code Opus 4.8 MEDIUM",
    description: "Apollo's twin: Opus 4.8 at medium effort for quicker, cheaper Claude Code takes.",
    kind: "claude-code",
    model: "claude-opus-4-8",
    effort: "medium",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "athena",
    id: "athena",
    name: "Athena",
    label: "Codex GPT 5.5 XHIGH",
    description: "Codex planner/doer with GPT 5.5 and xhigh reasoning effort.",
    kind: "codex",
    model: "gpt-5.5",
    effort: "xhigh",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "perseus",
    id: "perseus",
    name: "Perseus",
    label: "Codex GPT 5.5 HIGH",
    description: "Codex participant between Athena (xhigh) and Loki (medium): GPT 5.5 at high effort.",
    kind: "codex",
    model: "gpt-5.5",
    effort: "high",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "iris",
    id: "iris",
    name: "Iris",
    label: "Pi GPT 5.5 XHIGH",
    description: "Pi-backed GPT 5.5 participant with xhigh thinking and normal Pi skills available.",
    kind: "pi",
    model: "openai-codex/gpt-5.5",
    thinking: "xhigh",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "hermes",
    id: "hermes",
    name: "Hermes",
    label: "Pi GPT 5.5 HIGH",
    description: "Iris's fellow messenger: Pi-backed GPT 5.5 with high thinking.",
    kind: "pi",
    model: "openai-codex/gpt-5.5",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "eos",
    id: "eos",
    name: "Eos",
    label: "Pi GPT 5.5 MEDIUM",
    description: "Pi-backed GPT 5.5 with medium thinking for quicker takes.",
    kind: "pi",
    model: "openai-codex/gpt-5.5",
    thinking: "medium",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "luna",
    id: "luna",
    name: "Luna",
    label: "OpenCode Kimi K2.7 Code",
    description: "OpenCode-backed Kimi K2.7 Code participant — Moonshot's coding-first model (OpenRouter defines no effort variants for it).",
    kind: "opencode",
    model: "openrouter/moonshotai/kimi-k2.7-code",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },

  // --- Frontier models on the other engines that run them ------------------
  // Fable 5 on pi (anthropic provider) and OpenCode (OpenRouter). Both cap at xhigh.
  {
    preset: "orpheus",
    id: "orpheus",
    name: "Orpheus",
    label: "Pi Fable 5 XHIGH (Anthropic)",
    description: "The legendary bard: Pi-backed Claude Fable 5 with xhigh thinking; needs Anthropic auth in pi.",
    kind: "pi",
    model: "anthropic/claude-fable-5",
    thinking: "xhigh",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "linus",
    id: "linus",
    name: "Linus",
    label: "Pi Fable 5 HIGH (Anthropic)",
    description: "Orpheus's bard brother: Pi-backed Claude Fable 5 with high thinking; needs Anthropic auth in pi.",
    kind: "pi",
    model: "anthropic/claude-fable-5",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "erato",
    id: "erato",
    name: "Erato",
    label: "Pi Fable 5 MEDIUM (Anthropic)",
    description: "Muse of lyric poetry: Pi-backed Claude Fable 5 with medium thinking; needs Anthropic auth in pi.",
    kind: "pi",
    model: "anthropic/claude-fable-5",
    thinking: "medium",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "saga",
    id: "saga",
    name: "Saga",
    label: "OpenCode Fable 5 XHIGH",
    description: "Norse goddess of storytelling: OpenCode-backed Claude Fable 5 at xhigh variant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/anthropic/claude-fable-5",
    effort: "xhigh",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "gunnlod",
    id: "gunnlod",
    name: "Gunnlod",
    label: "OpenCode Fable 5 HIGH",
    description: "Guardian of the mead of poetry: OpenCode-backed Claude Fable 5 at high variant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/anthropic/claude-fable-5",
    effort: "high",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "kvasir",
    id: "kvasir",
    name: "Kvasir",
    label: "OpenCode Fable 5 MEDIUM",
    description: "Source of the mead of poetry: OpenCode-backed Claude Fable 5 at medium variant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/anthropic/claude-fable-5",
    effort: "medium",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  // Opus 4.8 on pi (anthropic provider; pi's thinking ceiling is xhigh, no "max").
  {
    preset: "kronos",
    id: "kronos",
    name: "Kronos",
    label: "Pi Opus 4.8 XHIGH (Anthropic)",
    description: "Pi-backed Claude Opus 4.8 with xhigh thinking; needs Anthropic auth in pi.",
    kind: "pi",
    model: "anthropic/claude-opus-4-8",
    thinking: "xhigh",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "atlas",
    id: "atlas",
    name: "Atlas",
    label: "Pi Opus 4.8 MEDIUM (Anthropic)",
    description: "Pi-backed Claude Opus 4.8 with medium thinking; needs Anthropic auth in pi.",
    kind: "pi",
    model: "anthropic/claude-opus-4-8",
    thinking: "medium",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  // Opus 4.8 on OpenCode (via OpenRouter; note the dotted 4.8 id on OpenRouter).
  // OpenRouter's effort scale tops out at xhigh — "max" exists only on claude-code.
  {
    preset: "baldr",
    id: "baldr",
    name: "Baldr",
    label: "OpenCode Opus 4.8 XHIGH",
    description: "OpenCode-backed Claude Opus 4.8 at xhigh variant, its OpenRouter ceiling.",
    kind: "opencode",
    model: "openrouter/anthropic/claude-opus-4.8",
    effort: "xhigh",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "vali",
    id: "vali",
    name: "Vali",
    label: "OpenCode Opus 4.8 MEDIUM",
    description: "OpenCode-backed Claude Opus 4.8 at medium variant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/anthropic/claude-opus-4.8",
    effort: "medium",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  // GPT 5.5 on OpenCode (via OpenRouter).
  {
    preset: "forseti",
    id: "forseti",
    name: "Forseti",
    label: "OpenCode GPT 5.5 XHIGH",
    description: "OpenCode-backed GPT 5.5 at xhigh variant (via OpenRouter); god of judgement for tough calls.",
    kind: "opencode",
    model: "openrouter/openai/gpt-5.5",
    effort: "xhigh",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "bragi",
    id: "bragi",
    name: "Bragi",
    label: "OpenCode GPT 5.5 HIGH",
    description: "OpenCode-backed GPT 5.5 at high variant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/openai/gpt-5.5",
    effort: "high",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "ullr",
    id: "ullr",
    name: "Ullr",
    label: "OpenCode GPT 5.5 MEDIUM",
    description: "OpenCode-backed GPT 5.5 at medium variant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/openai/gpt-5.5",
    effort: "medium",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },

  // --- Fast/cheap tier: quick gut-checks ----------------------------------
  {
    preset: "hermod",
    id: "hermod",
    name: "Hermod",
    label: "Claude Code Haiku 4.5 (fast)",
    description: "Fast, cheap Claude Code participant (Haiku) for quick gut-checks.",
    kind: "claude-code",
    model: "claude-haiku-4-5",
    effort: "low",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "loki",
    id: "loki",
    name: "Loki",
    label: "Codex GPT 5.5 (fast/medium)",
    description: "Nimbler Codex participant: GPT 5.5 at medium effort for quicker turnarounds.",
    kind: "codex",
    model: "gpt-5.5",
    effort: "medium",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "nike",
    id: "nike",
    name: "Nike",
    label: "Pi Gemini 3.5 Flash (fast)",
    description: "Swift, cheap Pi-backed Gemini 3.5 Flash for quick second opinions.",
    kind: "pi",
    model: "openrouter/google/gemini-3.5-flash",
    thinking: "low",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "freya",
    id: "freya",
    name: "Freya",
    label: "OpenCode DeepSeek V4 Flash (fast)",
    description: "Cheap, fast OpenCode-backed DeepSeek V4 Flash (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/deepseek/deepseek-v4-flash",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "zephyros",
    id: "zephyros",
    name: "Zephyros",
    label: "Pi DeepSeek V4 Flash (fast)",
    description: "Swift west wind: Pi-backed DeepSeek V4 Flash (via OpenRouter).",
    kind: "pi",
    model: "openrouter/deepseek/deepseek-v4-flash",
    thinking: "low",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "sif",
    id: "sif",
    name: "Sif",
    label: "OpenCode Gemini 3.5 Flash (fast)",
    description: "Swift, cheap OpenCode-backed Gemini 3.5 Flash at low variant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/google/gemini-3.5-flash",
    effort: "low",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },

  // --- pi model zoo (Greek names) — popular OpenRouter models via Pi -------
  {
    preset: "hades",
    id: "hades",
    name: "Hades",
    label: "Pi DeepSeek V4 Pro",
    description: "Pi-backed DeepSeek V4 Pro participant (via OpenRouter).",
    kind: "pi",
    model: "openrouter/deepseek/deepseek-v4-pro",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "helios",
    id: "helios",
    name: "Helios",
    label: "Pi Gemini 3.1 Pro",
    description: "Pi-backed Google Gemini 3.1 Pro participant (via OpenRouter).",
    kind: "pi",
    model: "openrouter/google/gemini-3.1-pro-preview",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "ares",
    id: "ares",
    name: "Ares",
    label: "Pi Grok 4.3",
    description: "Pi-backed xAI Grok 4.3 participant (via OpenRouter).",
    kind: "pi",
    model: "openrouter/x-ai/grok-4.3",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "hephaestus",
    id: "hephaestus",
    name: "Hephaestus",
    label: "Pi Qwen3.7 Max",
    description: "Pi-backed Qwen3.7 Max participant (via OpenRouter).",
    kind: "pi",
    model: "openrouter/qwen/qwen3.7-max",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "pan",
    id: "pan",
    name: "Pan",
    label: "Pi Llama 4 Maverick",
    description: "Pi-backed Meta Llama 4 Maverick participant (via OpenRouter).",
    kind: "pi",
    model: "openrouter/meta-llama/llama-4-maverick",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "aeolus",
    id: "aeolus",
    name: "Aeolus",
    label: "Pi Mistral Large",
    description: "Pi-backed Mistral Large participant (via OpenRouter); wind god for 'mistral'.",
    kind: "pi",
    model: "openrouter/mistralai/mistral-large-2512",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "metis",
    id: "metis",
    name: "Metis",
    label: "Pi MiniMax M3",
    description: "Pi-backed MiniMax M3 participant (via OpenRouter); goddess of cunning strategy for 'minimax'.",
    kind: "pi",
    model: "openrouter/minimax/minimax-m3",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "prometheus",
    id: "prometheus",
    name: "Prometheus",
    label: "Pi GLM 5.2",
    description: "Pi-backed Zhipu GLM 5.2 participant (via OpenRouter); the Titan who brought knowledge to mortals.",
    kind: "pi",
    model: "openrouter/z-ai/glm-5.2",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "selene",
    id: "selene",
    name: "Selene",
    label: "Pi Kimi K2.7 Code",
    description: "Greek moon goddess to Luna's Roman: Pi-backed Kimi K2.7 Code participant with high thinking (via OpenRouter).",
    kind: "pi",
    model: "openrouter/moonshotai/kimi-k2.7-code",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "daedalus",
    id: "daedalus",
    name: "Daedalus",
    label: "Pi Kimi K2.7 Code",
    description: "Greek master craftsman: Pi-backed Kimi K2.7 Code participant with high thinking (via OpenRouter).",
    kind: "pi",
    model: "openrouter/moonshotai/kimi-k2.7-code",
    thinking: "high",
    skillsPolicy: "default",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },

  // --- opencode model zoo (Norse names) — same models via OpenCode --------
  {
    preset: "odin",
    id: "odin",
    name: "Odin",
    label: "OpenCode DeepSeek V4 Pro",
    description: "OpenCode-backed DeepSeek V4 Pro participant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/deepseek/deepseek-v4-pro",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "heimdall",
    id: "heimdall",
    name: "Heimdall",
    label: "OpenCode Gemini 3.1 Pro",
    description: "OpenCode-backed Google Gemini 3.1 Pro participant at high variant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/google/gemini-3.1-pro-preview",
    effort: "high",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "thor",
    id: "thor",
    name: "Thor",
    label: "OpenCode Grok 4.3",
    description: "OpenCode-backed xAI Grok 4.3 participant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/x-ai/grok-4.3",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "tyr",
    id: "tyr",
    name: "Tyr",
    label: "OpenCode Qwen3.7 Max",
    description: "OpenCode-backed Qwen3.7 Max participant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/qwen/qwen3.7-max",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "vidar",
    id: "vidar",
    name: "Vidar",
    label: "OpenCode Llama 4 Maverick",
    description: "OpenCode-backed Meta Llama 4 Maverick participant (via OpenRouter).",
    kind: "opencode",
    model: "openrouter/meta-llama/llama-4-maverick",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "njord",
    id: "njord",
    name: "Njord",
    label: "OpenCode Mistral Large",
    description: "OpenCode-backed Mistral Large participant (via OpenRouter); sea/wind god for 'mistral'.",
    kind: "opencode",
    model: "openrouter/mistralai/mistral-large-2512",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
  {
    preset: "mimir",
    id: "mimir",
    name: "Mimir",
    label: "OpenCode MiniMax M3",
    description: "OpenCode-backed MiniMax M3 participant (via OpenRouter); god of wisdom for 'minimax'.",
    kind: "opencode",
    model: "openrouter/minimax/minimax-m3",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },

  // --- Image generation (Codex backend → gpt-image-2) ---------------------
  {
    preset: "pygmalion",
    id: "pygmalion",
    name: "Pygmalion",
    label: "Image — gpt-image-2 (via Codex login)",
    description: "Generates images with gpt-image-2 through your existing openai-codex login. Accepts optional reference images (`--image <path>`, repeatable) to edit/condition on. The model field is only the trigger model; the image backend is always gpt-image-2.",
    kind: "image",
    model: "gpt-5.5",
    toolsPolicy: "workspace-write",
    timeoutMs: T,
  },
];

export function getPreset(ref) {
  const id = slugify(stripMention(ref));
  return PARTICIPANT_PRESETS.find((preset) => preset.preset === id || preset.id === id || slugify(preset.name) === id) ?? null;
}

export function listPresetIds() {
  return PARTICIPANT_PRESETS.map((preset) => preset.preset);
}

export function participantFromPreset(ref, overrides = {}) {
  const preset = getPreset(ref);
  if (!preset) return null;
  const nameOverride = stringOverride(overrides.name);
  const idOverride = stringOverride(overrides.id);
  const name = nameOverride ?? preset.name;
  // Keep the preset's canonical id; only derive a new id when the caller renames (--name) or sets
  // an explicit id.
  const id = slugify(idOverride ?? nameOverride ?? preset.id);
  const participant = {
    ...preset,
    ...allowedOverrides(overrides),
    preset: preset.preset,
    id,
    name,
    kind: preset.kind,
    model: preset.model,
    effort: preset.effort,
    thinking: preset.thinking,
    toolsPolicy: preset.toolsPolicy,
    skillsPolicy: preset.skillsPolicy,
  };
  delete participant.label;
  return participant;
}

function stringOverride(value) {
  if (value === undefined || value === null || value === true) return undefined;
  const trimmed = String(value).trim();
  return trimmed || undefined;
}

function allowedOverrides(overrides) {
  const result = {};
  for (const key of ["cwd", "timeoutMs", "description"]) {
    if (overrides[key] !== undefined) result[key] = overrides[key];
  }
  return result;
}

export function formatPresetLine(preset) {
  const effort = preset.effort ? ` effort=${preset.effort}` : preset.thinking ? ` thinking=${preset.thinking}` : "";
  const skills = preset.kind === "pi" ? ` skills=${preset.skillsPolicy ?? "default"}` : "";
  return `- ${preset.preset} → @${preset.id} (${preset.name}): ${preset.label} [${preset.kind} model=${preset.model}${effort}${skills}]`;
}

export function formatPresets() {
  return ["# ConsensFlow participant presets", "", ...PARTICIPANT_PRESETS.map(formatPresetLine), "", "Add one with `/consensflow:participants add <preset>`, or `/consensflow:participants add all`."].join("\n");
}
